# Generated by Django 3.2.8 on 2021-10-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nik',
            field=models.IntegerField(max_length=20),
        ),
    ]
